### ISSUE TITLE
Duplicated apt

### ISSUE THREAD

**Issue by hugok79** [rbtylee/quickstart_local#1]
https://github.com/rbtylee/quickstart_local/blob/652cbf66dce0d162cebb6a9b68cd4ca6cb7f24ca/quickstartEN/software.html#L178

Since **apt-get** has been removed there is no need for **apt** to be duplicated! ba94649fcec9f1566cdca76964fc85d58647e31a

**Comment by rbtylee** [comment]
Yes We will fix that. I was ina rush port all the po files in translated HTML files. We still have some minor changes to make in the EN versions and then get that into the localized HTML.

**Comment by rbtylee** [comment]
The last two commits fixed this in all languages so far. Took a guess at the languages I do not speak.

**Comment by hugok79** [comment]
Thanks!
