### ISSUE TITLE
"All" menu

### ISSUE THREAD

**Issue by batden** [rbtylee/quickstart_local#12]
in moksha.html -> 'The Entire Desktop is the Menu' section:

'...the mouse-binding "Show Main Menu", can be easily removed/configured in:
  Main Menu -> Settings -> **All** -> Input -> Mouse Bindings. '

Am I wrong or the All module (Configuration Panel) is not (yet?) available / loaded in Moksha BL 7.0 RC ?
Will it be in the final release?

**Comment by rbtylee** [comment]
In e17 that was the default Setting (displaying the Settings Panel in the Main Menu in this way). In Moksha, one has to set the configuration to turn this on. This is in the Settings Panel under the **Menus tab -> Configuration Panel**. Note the location for this entry is not the same as it was in e17 or currently is in e25, it made more sense to us to move to the Menus tab. Personally, I always enable this as I use it. Disabling it goes back to Jeff's attempt to 'simplify' Moksha's menu. I suppose we need to reword all occurrences of "_Main Menu -> Settings -> **All** ->.._." in this guide.

**Comment by batden** [comment]
Thanks for the clarification. Indeed, the Menus tab is a better location.
