### ISSUE TITLE
Missing space between images (moksha.html)

### ISSUE THREAD

**Issue by hugok79** [rbtylee/quickstart_local#15]
**See picture below:**

![Captura de ecrã 2023-07-20 134758](https://github.com/rbtylee/quickstart_local/assets/16929048/b5c3e3b0-3385-4702-a2de-7d9d35918a2c)

**Comment by thewaiter** [comment]
OK, I have added a solution to EN and SK folders:
https://github.com/rbtylee/quickstart_local/commit/d3dfc12d6d8289cb7d03b260771f4b7c160676d3

**Comment by hugok79** [comment]
Fixed
