### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by batden** [rbtylee/quickstart_local#16]
in everything.html: " (...) then enter into the Quick Launcher" -> enter **term** into...
in quickfaq.html: " (...) **unil** the Ubuntu LTS base" -> until...

**Comment by thewaiter** [comment]
Are you OK with this fixes?
https://github.com/rbtylee/quickstart_local/commit/0f723482e45790f2fdc940925e011f1181b7b7f6

**Comment by batden** [comment]
All correct.
