### ISSUE TITLE
Desktop launcher translation

### ISSUE THREAD

**Issue by hugok79** [rbtylee/quickstart_local#20]
In the BL 7 RC live session the launcher (/home/bodhi/Desktop/bodhi-help.desktop) "Help" is badly translated into Portuguese(PT). Where is the word "Socorro" translated? Where is the source of this file?

![shot-2023-07-20_15-29-35](https://github.com/rbtylee/quickstart_local/assets/16929048/62eb5a71-6f92-4ad9-9811-11787a6e4e36)

**Comment by rbtylee** [comment]
See https://github.com/BodhiDev/bodhi-profile-iso

The desktop file is https://github.com/BodhiDev/bodhi-profile-iso/blob/main/data/bodhi/desktop/bodhi-help.desktop

I do not always keep this repo up to date with what is on the ISO but the parts that may be dated are the specifics of the Moksha profile. The desktop files have not changed in a long time. Might even go back to Jeff''s time as lead dev.

**Comment by hugok79** [comment]
Thanks for the explanation @rbtylee
In any case I have created a PR https://github.com/BodhiDev/bodhi-profile-iso/pull/1 to improve the Portuguese translation.

**Comment by hugok79** [comment]
Fixed

**Comment by rbtylee** [comment]
Thanks again :D
