### ISSUE TITLE
"Install Now" button

### ISSUE THREAD

**Issue by hugok79** [rbtylee/quickstart_local#27]
Could the words "Install Now" be translated? So the button could also be translated...

![Captura de ecrã 2023-07-26 135203](https://github.com/rbtylee/quickstart_local/assets/16929048/2f927179-401a-4eff-b7e3-29f4570cf71c)

![Captura de ecrã 2023-07-26 135232](https://github.com/rbtylee/quickstart_local/assets/16929048/dd05b717-ba27-48fb-953d-79afa26e43ae)

https://github.com/rbtylee/quickstart_local/blob/cc419394f8ea8b0ec911ae16f3b18ceef6133023/quickstartEN/software.html#L134

https://github.com/rbtylee/quickstart_local/blob/cc419394f8ea8b0ec911ae16f3b18ceef6133023/quickstartEN/software.html#L170

**Comment by thewaiter** [comment]
happy translating:
https://github.com/rbtylee/quickstart_local/commit/b6620122711cc6e199d47b395a58e372756e7c0a

**Comment by hugok79** [comment]
Thanks
