### ISSUE TITLE
Different commands info

### ISSUE THREAD

**Issue by hugok79** [rbtylee/quickstart_local#41]
@rbtylee 
The commands differ! One says `sudo apt dist-upgrade` and the other says `sudo apt full-upgrade`

https://github.com/rbtylee/quickstart_local/blob/4bef619ffa54fde1831b1182537c06b3daf5f37e/quickstartEN/landing.html#L47

https://github.com/rbtylee/quickstart_local/blob/4bef619ffa54fde1831b1182537c06b3daf5f37e/quickstartEN/software.html#L75

**Comment by thewaiter** [comment]
corrected
