### ISSUE TITLE
Request and typo

### ISSUE THREAD

**Issue by batden** [rbtylee/quickstart_local#6]
No translators in QuickStart Guide Contributors (appendix.html)!?
Typo in landing.html: " Bodhi uses _itables_".

**Comment by rbtylee** [comment]
I will address these after work today. Translations are new so yes should be added to the Contributors list :)

**Comment by thewaiter** [comment]
Iptables corrected in all affected files. THX

**Comment by rbtylee** [comment]
Translation section added to the EN appendix.html file.
